"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Lightbulb, ArrowLeft, Download, Edit, CheckCircle, FileText } from "lucide-react"
import { toast } from "@/hooks/use-toast"

export default function ProposalPage() {
  const router = useRouter()
  const [proposal, setProposal] = useState("")
  const [proposalData, setProposalData] = useState<any>(null)
  const [isDownloading, setIsDownloading] = useState(false)

  useEffect(() => {
    const savedProposal = sessionStorage.getItem("generatedProposal")
    const savedData = sessionStorage.getItem("proposalData")

    if (!savedProposal) {
      router.push("/generate")
      return
    }

    setProposal(savedProposal)
    if (savedData) {
      setProposalData(JSON.parse(savedData))
    }
  }, [router])

  const handleDownloadPDF = async () => {
    setIsDownloading(true)

    try {
      // Create a simple HTML version for PDF generation
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Business Proposal</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; color: #333; }
            h1 { color: #4F46E5; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
            h2 { color: #374151; margin-top: 30px; }
            h3 { color: #6B7280; }
            p { margin-bottom: 15px; }
            .header { text-align: center; margin-bottom: 40px; }
            .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #6B7280; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Business Proposal</h1>
            <p>Generated by PitchPal</p>
          </div>
          ${proposal.replace(/\n/g, "<br>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}
          <div class="footer">
            <p>This proposal was generated using PitchPal AI Business Proposal Generator</p>
          </div>
        </body>
        </html>
      `

      // Create a blob and download
      const blob = new Blob([htmlContent], { type: "text/html" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = "business-proposal.html"
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      toast({
        title: "✅ Proposal Ready!",
        description: "Your business proposal has been downloaded successfully.",
      })
    } catch (error) {
      console.error("Error downloading proposal:", error)
      toast({
        title: "Download Failed",
        description: "There was an error downloading your proposal. Please try again.",
        variant: "destructive",
      })
    } finally {
      setIsDownloading(false)
    }
  }

  const formatProposal = (text: string) => {
    return text.split("\n").map((line, index) => {
      if (line.startsWith("# ")) {
        return (
          <h1 key={index} className="text-3xl font-bold text-indigo-600 mb-4 mt-8 first:mt-0">
            {line.substring(2)}
          </h1>
        )
      } else if (line.startsWith("## ")) {
        return (
          <h2 key={index} className="text-2xl font-semibold text-gray-800 mb-3 mt-6">
            {line.substring(3)}
          </h2>
        )
      } else if (line.startsWith("### ")) {
        return (
          <h3 key={index} className="text-xl font-medium text-gray-700 mb-2 mt-4">
            {line.substring(4)}
          </h3>
        )
      } else if (line.startsWith("- ")) {
        return (
          <li key={index} className="ml-4 mb-1">
            {line.substring(2)}
          </li>
        )
      } else if (line.trim() === "") {
        return <br key={index} />
      } else {
        return (
          <p key={index} className="mb-3 text-gray-700 leading-relaxed">
            {line}
          </p>
        )
      }
    })
  }

  if (!proposal) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="border-b bg-white sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/generate" className="flex items-center space-x-2">
            <ArrowLeft className="h-5 w-5 text-gray-600" />
            <Lightbulb className="h-8 w-8 text-indigo-600" />
            <h1 className="text-2xl font-bold text-gray-900">PitchPal</h1>
          </Link>

          <div className="flex items-center space-x-3">
            <Button variant="outline" onClick={() => router.push("/generate")} className="flex items-center space-x-2">
              <Edit className="h-4 w-4" />
              <span>Edit & Regenerate</span>
            </Button>
            <Button
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className="bg-emerald-600 hover:bg-emerald-700 text-white flex items-center space-x-2"
            >
              {isDownloading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  <span>Downloading...</span>
                </>
              ) : (
                <>
                  <Download className="h-4 w-4" />
                  <span>Download PDF</span>
                </>
              )}
            </Button>
          </div>
        </div>
      </header>

      {/* Success Toast */}
      <div className="bg-emerald-50 border-l-4 border-emerald-400 p-4 mb-6">
        <div className="flex items-center">
          <CheckCircle className="h-5 w-5 text-emerald-400 mr-3" />
          <div>
            <p className="text-emerald-800 font-medium">
              ✅ {proposalData?.rfpFile ? "RFP Response Ready!" : "Proposal Ready!"}
            </p>
            <p className="text-emerald-700 text-sm">
              Your {proposalData?.rfpFile ? "RFP response" : "business proposal"} has been generated successfully.
              Download your PDF below.
            </p>
          </div>
        </div>
      </div>

      {/* Proposal Content */}
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <Card className="shadow-lg">
            <CardContent className="p-8 md:p-12">
              {proposalData?.rfpFile && (
                <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                  <div className="flex items-center space-x-2 text-blue-800">
                    <FileText className="h-5 w-5" />
                    <span className="font-medium">RFP Response for: {proposalData.rfpFile.name}</span>
                  </div>
                </div>
              )}
              <div className="prose prose-lg max-w-none">{formatProposal(proposal)}</div>
            </CardContent>
          </Card>

          {/* Action Buttons */}
          <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              size="lg"
              className="bg-emerald-600 hover:bg-emerald-700 text-white"
            >
              {isDownloading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Downloading...
                </>
              ) : (
                <>
                  <Download className="mr-2 h-4 w-4" />
                  Download as PDF
                </>
              )}
            </Button>
            <Button variant="outline" size="lg" onClick={() => router.push("/generate")}>
              <Edit className="mr-2 h-4 w-4" />
              Edit and Regenerate
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
